# knight helmet = HEAD_PLATE_SET2
# assassin hood = HEAD_LEATHER_SET3
# stalker hood = HEAD_LEATHER_MORGANA
# royal hood = HEAD_LEATHER_ROYAL
# scholar cowl = HEAD_CLOTH_SET1
# royal cowl = HEAD_CLOTH_ROYAL
# soldier armor = ARMOR_PLATE_SET1 ✅
# hellion jacket = ARMOR_LEATHER_HELL ✅
# specter jacket = ARMOR_LEATHER_UNDEAD ✅
# scholar robe = ARMOR_CLOTH_SET1 ✅
# cleric robe = ARMOR_CLOTH_SET2 ✅
# hunter shoes = SHOES_LEATHER_SET2
# scholar sandals = SHOES_CLOTH_SET1
# royal sandals = SHOES_CLOTH_ROYAL

# clarent = MAIN_SCIMITAR_MORGANA
# galatines = 2H_DUALSCIMITAR_UNDEAD
# facebreaker = OFF_SPIKEDSHIELD_MORGANA
# halberd = 2H_HALBERD
# bearpaws = 2H_DUALAXE_KEEPER
# realmbraker = 2H_AXE_AVALON
# crossbow = 2H_CROSSBOW
# weeping = 2H_REPEATINGCROSSBOW_UNDEAD
# siege = 2H_CROSSBOWLARGE_MORGANA
# energy shaper = CROSSBOW_CANNON_AVALON
# mistpiercer = 2H_BOW_AVALON
# bloodletter = MAIN_RAPIER_MORGANA
# bridled fury = 2H_DAGGER_KATAR_AVALON
# brimstone = 2H_FIRESTAFF_HELL
# blazing = 2H_INFERNOSTAFF_MORGANA
# dawnsong = 2H_FIRE_RINGPAIR_AVALON
# perma = 2H_ICECRYSTAL_UNDEAD
# damnation = 2H_CURSEDSTAFF_MORGANA

ARMOR_list = ['ARMOR_PLATE_SET1', 'ARMOR_LEATHER_HELL', 'ARMOR_LEATHER_UNDEAD', 'ARMOR_CLOTH_SET1', 'ARMOR_CLOTH_SET2']

H_list = ['MAIN_SCIMITAR_MORGANA', '2H_DUALSCIMITAR_UNDEAD', 'OFF_SPIKEDSHIELD_MORGANA', '2H_HALBERD', '2H_DUALAXE_KEEPER',
          '2H_AXE_AVALON', '2H_CROSSBOW', '2H_REPEATINGCROSSBOW_UNDEAD', '2H_CROSSBOWLARGE_MORGANA', '2H_CROSSBOW_CANNON_AVALON',
          '2H_BOW_AVALON', 'MAIN_RAPIER_MORGANA', '2H_DAGGER_KATAR_AVALON', '2H_FIRESTAFF_HELL', '2H_INFERNOSTAFF_MORGANA',
          '2H_FIRE_RINGPAIR_AVALON', '2H_ICECRYSTAL_UNDEAD', '2H_CURSEDSTAFF_MORGANA']
